version: 2.1

jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9.0/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install deps
          command: |  # use pipenv to install dependencies
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run: python3 billing_system.py
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            # - "/usr/local/lib/python3.9.0/site-packages"
 
  test1:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_1.py
  test2:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_2.py

  get_artifact:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: rm -rf .git
      - store_artifacts:
          path: /home/circleci/artifact
          destination: artifact-file

workflows:
  build_and_test1:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - approval:
          type: approval
          requires:
              - test1
              - test2
      - get_artifact:
          requires:
            - approval

  # build_and_test2:
  #   jobs:
  #     - build
  #     - test1:
  #         requires:
  #           - build
  #     - test2:
  #         requires:
  #           - build
  #     - approval:
  #         type: approval
  #         requires:
  #             - test1
  #             - test2
  #     - get_artifact:
  #         requires:
  #           - approval
          
