version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - run: python3 billing_system.py
  test1:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_1.py
  test2:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_2.py

workflows:
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
