version: 2.1

jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run:  v /tmp/.X11-unix:/tmp/.X11-unix
      - run: -e DISPLAY=unix$DISPLAY
      - run: $ sudo apt-get install x11-xserver-utils
      - run: $ xhost +
      - run: export MPLBACKEND='Agg'
      - run: python3 billing_system.py
  test1:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_1.py
  test2:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_2.py

workflows:
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
