version: 2.1

jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: ls
      - run: python3 billing_system.py
 
  test1:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_1.py
  test2:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_2.py

  get_artifact:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: rm -rf .git
      - store_artifacts:
          path: /home/circleci/artifact
          destination: artifact-file

workflows:
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      -approval:
        type: approval
        requires:
            - test1
            - test2
      - get_artifact:
          requires:
            - approval
          
