version: '2.1'
#define commands globally so that we can use it in multiple jobs
commands:
  param_ex:
    steps:
      - run:
          command: |  
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
jobs:
  build:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout 
      - param_ex
      - run:
          name: Running main file
          command: python3 billing_system.py


  unit-test-1:
      docker:
        - image: cimg/python:3.11.2  
      steps:
        - checkout
        - run:
            name: Run Unit Test 1 
            command: python3 test_billing_system_1.py 

  unit-test-2:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: Run Unit Test 2 
          command: python3 test_billing_system_2.py   

  create_artifacts_and_zip:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build . -t ${CIRCLE_BRANCH}_${Environment}:${CIRCLE_BUILD_NUM}
          docker images 
          mkdir -p cci_image
          docker save -o ${CIRCLE_BRANCH}_{Environment}.tar ${CIRCLE_BRANCH}_${Environment}:{CIRCLE_BUILD_NUM}
          mv ${CIRCLE_BRANCH}_{Environment}.tar cci_image/
          ls -ltrh cci_image
      - store_artifacts:
          path: cci_image/


  build_cache:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
      - param_ex
      - run:
          name: Running main file
          command: python3 billing_system.py
      - save_cache:
          key: python-requirements-V1-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python3.10/site-packages"
            - "/usr/local/lib/site-python"         


workflows:
  version: 2
  akhil-caselet1-cci: 
    jobs:
      - build
      - unit-test-1: 
          requires:
            - build
      - unit-test-2: 
          requires:
            - build
      - need_approval:
          type: approval
          requires: 
            - unit-test-1
            - unit-test-2  
      - create_artifacts_and_zip:
          requires:
            - need_approval

  workflow_two:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters: 
            branches:
              only:
                - akhil_caselet     
    jobs:
      - build_cache
      - unit-test-1:
          requires:
            - build_cache
      - unit-test-2:
          requires:
            - unit-test-1
      - approval:
          type: approval
          requires:
              - unit-test-2
      - create_artifacts_and_zip:
          requires:
            - approval                

