version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run : 
          name: installing pip and requirements
          command: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Running application
          command: |
            python billing_system.py
  test:
    docker:
      - image: cimg/python:3.10.1
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Running tests 1
          command: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            python test_billing_system_1.py
      - run:
          name: Running test 2
          command: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            python test_billing_system_2.py
  creating_artifacts:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run: rm -rf .git
      - store_artifacts:
          path: /images
          destination: artifact-file
workflows:
  # run_test:
  #   jobs:
  #     - build
  #     - approval:
  #         type: approval
  #         requires:
  #           - build
  #     - test:
  #         requires: 
  #           - approval
  building_artifacts:
    jobs:
      - creating_artifacts