version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys: 
            - cache-v1-{{ checksum "requirements.txt" }}
      - run : 
          name: installing pip and requirements
          command: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Running application main file
          command: |
            python billing_system.py
      - save_cache:
          key: cache-v1-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
  run-test1:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys: 
            - cache-v1-{{ checksum "requirements.txt" }}
      - run:
          name: Running tests 1
          command: python test_billing_system_1.py
      - save_cache:
          key: cache-v1-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
  run-test2:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys: 
            - cache-v1-{{ checksum "requirements.txt" }}
      - run:
          name: Running test 2
          command: python test_billing_system_2.py
      - save_cache:
          key: cache-v1-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
  creating_artifacts:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Package source files and zip
          command: tar -cvzf /tmp/source.tar .
      - store_artifacts:
          path: /tmp/source.tar
          
workflows:
  workflow1:
    jobs:
      - build
      - run-test1:
          requires: 
            - build
      - run-test2:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - run-test1
            - run-test2
      - creating_artifacts:
          requires:
            - approval
  workflow2:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters: 
            branches:
              only:
                - ankita_caselet
    jobs:
      - build
      - run-test1:
          requires: 
            - build
      - run-test2:
          requires:
            - run-test1
      - approval:
          type: approval
          requires:
            - run-test2
      - creating_artifacts:
          requires:
            - approval