version: 2.1

jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run:
          name: install deps
          command: |  # use pipenv to install dependencies
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run: python3 billing_system.py
  test1:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_1.py
  
  test2:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_2.py

workflows:
  build_and_test_workflow1:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - approval:
          type: approval
          requires:
              - test1
              - test2
      - docker_build:
          requires:
            - approval