version: 2.1

jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: ls
      - run: python3 billing_system.py
      - run: cd .. && ls
  test1:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_1.py
  test2:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_2.py

  get_artifact:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      # - run:
      #     name: Creating Dummy Artifacts
      #     command: |
      #       mkdir ~/circleci-project-setup/artifacts;
      #       cp -r . ~/circleci-project-setup/artifacts
      - store_artifacts:
          path: ./circleci-project-setup
      # - store_artifacts:
      #     path: ~/circleci-project-setup/artifacts

workflows:
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - get_artifact:
          requires:
            - test1
            - test2
