version: 2.1

jobs:
  execute-main:
    docker:
      - image: python 
    steps:
      - checkout 
      - run: python billing_system.py 
  execute-test:
    docker:
      - image: python 
    parameters:
      test-file: 
        type: string    
    steps:
      - checkout 
      - run: python << parameters.test-file >>    

workflows:
  first-workflow:
    jobs:
      - execute-main 
      - execute-test: 
          test-file: test_billing_system_1.py
      - execute-test: 
          test-file: test_billing_system_2.py