version: 2.1

jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run:
          name: install deps
          command: |  # use pipenv to install dependencies
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run: python3 billing_system.py

  build_cache:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps11-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install deps
          command: |  # use pipenv to install dependencies
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run: python3 billing_system.py
      - save_cache:
          key: deps11-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.9/site-packages"
 
  test1:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_1.py
  test2:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: python3 test_billing_system_2.py

  get_artifact:
    working_directory: ~/circleci-project-setup
    docker:
      - image: "circleci/python:3.9.0"
    steps:
      - checkout
      - run: rm -rf .git
      - store_artifacts:
          path: /home/circleci/artifact
          destination: artifact-file
  
  docker_build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - run: docker build . -t rishab_cci
      - run: docker image ls
      - run: 
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/rishab_cci.tar rishab_cci
            ls
            cd /caches
            ls
      - store_artifacts:
          path: /caches/rishab_cci.tar
          destination: artifact-file

workflows:
  build_and_test1:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - approval:
          type: approval
          requires:
              - test1
              - test2
      - docker_build
      # - get_artifact:
      #     requires:
      #       - approval

  # build_and_test2:
  #   jobs:
  #     - build_cache
  #     - test1:
  #         requires:
  #           - build_cache
  #     - test2:
  #         requires:
  #           - build_cache
  #     - approval:
  #         type: approval
  #         requires:
  #             - test1
  #             - test2
  #     - get_artifact:
  #         requires:
  #           - approval
          
