version: 2.1

jobs:
  execute-main:
    docker:
      - image: python 
    steps:
      - checkout 
      - run: python billing_system.py 
  execute-test:
    docker:
      - image: python 
    parameters:
      test-file: 
        type: string    
    steps:
      - checkout 
      - run: python << parameters.test-file >>
  publish-artifact:
    docker:
      - image: python 
    steps:
      - checkout 
      - run: tar -cvzf first-artifact.tar .
      - store_artifacts:
          path: first-artifact.tar

workflows:
  first-workflow:
    jobs:
      - execute-main 
      - execute-test: 
          name: "execute-test-1"
          test-file: test_billing_system_1.py
          requires:
            - execute-main
      - execute-test: 
          name: "execute-test-2"
          test-file: test_billing_system_2.py
          requires:
            - execute-main
      - hold: 
          type: approval
          requires: 
            - execute-test-1
            - execute-test-2
      - publish-artifact:
          requires:
            - hold
          

      